package view.Panels.Desafio;

import controller.TodoController;
import exceptions.EntityNotFoundException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Desafio;
import model.Usuario;
import view.Dashboard;

/**
 *
 * @author boli6
 */
public class EditarDesafio extends javax.swing.JPanel {

    private Dashboard dashboard;
    private TodoController controller;
    private Usuario u;
    private Desafio d;

    /**
     * Creates new form EditarDesafio
     */
    public EditarDesafio(Dashboard dashboard, TodoController tc, Usuario u, Desafio d) {
        this.controller = tc;
        this.u = u;
        this.dashboard = dashboard;
        this.d = d;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Banner = new javax.swing.JLabel();
        jPanelTopo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelEditarDesafio = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelNome2 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jFormattedTextFieldInicioData = new javax.swing.JFormattedTextField();
        jLabelNome = new javax.swing.JLabel();
        jFormattedTextFieldFimData = new javax.swing.JFormattedTextField();
        Criar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(653, 606));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Design sem nome.gif"))); // NOI18N

        jPanelTopo.setBackground(new java.awt.Color(0, 17, 33));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Desafio Grande.gif"))); // NOI18N

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jLabelEditarDesafio.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabelEditarDesafio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEditarDesafio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEditarDesafio.setText("Editar Desafio");
        jLabelEditarDesafio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEditarDesafio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEditarDesafio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextFieldDescricao.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDescricao.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jTextFieldDescricao.setForeground(new java.awt.Color(0, 17, 33));
        jTextFieldDescricao.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));

        jLabelNome1.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabelNome1.setForeground(new java.awt.Color(0, 17, 33));
        jLabelNome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome1.setText("Início:");

        jLabelNome2.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabelNome2.setForeground(new java.awt.Color(0, 17, 33));
        jLabelNome2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome2.setText("Fim:");

        Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        Cancelar.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Cancelar.setForeground(new java.awt.Color(0, 17, 33));
        Cancelar.setText("Cancelar");
        Cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jFormattedTextFieldInicioData.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldInicioData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        jFormattedTextFieldInicioData.setForeground(new java.awt.Color(0, 17, 33));
        try {
            jFormattedTextFieldInicioData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldInicioData.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N

        jLabelNome.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(0, 17, 33));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Nome:");

        jFormattedTextFieldFimData.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedTextFieldFimData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        jFormattedTextFieldFimData.setForeground(new java.awt.Color(0, 17, 33));
        try {
            jFormattedTextFieldFimData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldFimData.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N

        Criar.setBackground(new java.awt.Color(255, 255, 255));
        Criar.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        Criar.setForeground(new java.awt.Color(0, 17, 33));
        Criar.setText("Editar");
        Criar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarActionPerformed(evt);
            }
        });

        jTextFieldNome.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNome.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jTextFieldNome.setForeground(new java.awt.Color(0, 17, 33));
        jTextFieldNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));

        jLabelDescricao.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(0, 17, 33));
        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescricao.setText("Descrição:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Banner)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jFormattedTextFieldFimData, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabelNome1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jFormattedTextFieldInicioData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescricao)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome1)
                    .addComponent(jFormattedTextFieldInicioData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome2)
                    .addComponent(jFormattedTextFieldFimData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar)
                    .addComponent(Criar))
                .addGap(18, 18, 18)
                .addComponent(Banner, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        Desafios desafios = new Desafios(dashboard, controller, u);
        dashboard.abrirPanelForm(desafios);
    }//GEN-LAST:event_CancelarActionPerformed

    private void CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarActionPerformed
        try {
            Desafio new_d = new Desafio();
            new_d.setId(this.d.getId());

            if (!this.jTextFieldNome.getText().isEmpty()) {
                new_d.setNome(jTextFieldNome.getText());
            }

            if (!this.jTextFieldDescricao.getText().isEmpty()) {
                new_d.setDescricao(jTextFieldDescricao.getText());
            }

            String data_inicio = this.jFormattedTextFieldInicioData.getText().replaceAll("/", "");
            if (!data_inicio.isBlank()) {
                new_d.setDataInicio(LocalDate.parse(
                        jFormattedTextFieldInicioData.getText(),
                        DateTimeFormatter.ofPattern("dd/MM/yyyy")
                ));
            }

            String data_fim = this.jFormattedTextFieldFimData.getText().replaceAll("/", "");
            if (!data_fim.isBlank()) {
                new_d.setDataFim(LocalDate.parse(
                        jFormattedTextFieldFimData.getText(),
                        DateTimeFormatter.ofPattern("dd/MM/yyyy")
                ));
            }

            controller.updateChallenge(new_d);

            Desafios desafios = new Desafios(dashboard, controller, u);
            dashboard.abrirPanelForm(desafios);
        } catch (SQLException | EntityNotFoundException ex) {
            Logger.getLogger(EditarDesafio.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_CriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banner;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Criar;
    private javax.swing.JFormattedTextField jFormattedTextFieldFimData;
    private javax.swing.JFormattedTextField jFormattedTextFieldInicioData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelEditarDesafio;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
