package view;

import controller.TodoController;
import java.awt.Color;
import javax.swing.JPanel;
import model.Usuario;
import view.Panels.Desafio.Desafios;
import view.Panels.User.EditarUser;
import view.Panels.Grupo.Grupos;
import view.Panels.relatorio.Relatorio;

/**
 *
 * @author boli6
 */
public class Dashboard extends javax.swing.JFrame {

    private TodoController controller;
    private Usuario u;
    
    /**
     * Creates new form Dashboard
     */
    public Dashboard(TodoController tc, Usuario u) {
        this.controller = tc;
        this.u = u;
        initComponents();
        updateInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jPanelUsuario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jLabelEmailUsuario = new javax.swing.JLabel();
        jButtonGrupos = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonEditarUsuario = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonDesafios = new javax.swing.JButton();
        jButtonRelatorio = new javax.swing.JButton();
        jPanelLogo = new javax.swing.JPanel();
        ImagemLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelCentral.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCentral.setPreferredSize(new java.awt.Dimension(900, 600));

        jPanelUsuario.setBackground(new java.awt.Color(0, 17, 32));
        jPanelUsuario.setPreferredSize(new java.awt.Dimension(241, 600));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-usuário-homem-com-círculo-100.png"))); // NOI18N

        jLabelNomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNomeUsuario.setText("CADU");

        jLabelEmailUsuario.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        jLabelEmailUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmailUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmailUsuario.setText("carlosegm3012@gmail.com");

        jButtonGrupos.setBackground(new java.awt.Color(0, 17, 32));
        jButtonGrupos.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButtonGrupos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-tarefa-25.png"))); // NOI18N
        jButtonGrupos.setText("  Grupos");
        jButtonGrupos.setBorder(null);
        jButtonGrupos.setBorderPainted(false);
        jButtonGrupos.setContentAreaFilled(false);
        jButtonGrupos.setFocusPainted(false);
        jButtonGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGruposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonGruposMouseExited(evt);
            }
        });
        jButtonGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGruposActionPerformed(evt);
            }
        });

        jButtonSair.setBackground(new java.awt.Color(0, 17, 32));
        jButtonSair.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButtonSair.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-abrir-painel-25.png"))); // NOI18N
        jButtonSair.setText("  Sair");
        jButtonSair.setBorder(null);
        jButtonSair.setBorderPainted(false);
        jButtonSair.setContentAreaFilled(false);
        jButtonSair.setFocusPainted(false);
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSairMouseExited(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonEditarUsuario.setBackground(new java.awt.Color(0, 17, 32));
        jButtonEditarUsuario.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButtonEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-editar-usuário-masculino-25.png"))); // NOI18N
        jButtonEditarUsuario.setText("  Usuário");
        jButtonEditarUsuario.setToolTipText("");
        jButtonEditarUsuario.setBorder(null);
        jButtonEditarUsuario.setBorderPainted(false);
        jButtonEditarUsuario.setContentAreaFilled(false);
        jButtonEditarUsuario.setFocusPainted(false);
        jButtonEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonEditarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonEditarUsuarioMouseExited(evt);
            }
        });
        jButtonEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarUsuarioActionPerformed(evt);
            }
        });

        jButtonHome.setBackground(new java.awt.Color(0, 17, 32));
        jButtonHome.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        jButtonHome.setText("  Home");
        jButtonHome.setToolTipText("");
        jButtonHome.setBorder(null);
        jButtonHome.setBorderPainted(false);
        jButtonHome.setContentAreaFilled(false);
        jButtonHome.setFocusPainted(false);
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonHomeMouseExited(evt);
            }
        });
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonDesafios.setBackground(new java.awt.Color(0, 17, 32));
        jButtonDesafios.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButtonDesafios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDesafios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/desafio.png"))); // NOI18N
        jButtonDesafios.setText("  Desafios");
        jButtonDesafios.setToolTipText("");
        jButtonDesafios.setBorder(null);
        jButtonDesafios.setBorderPainted(false);
        jButtonDesafios.setContentAreaFilled(false);
        jButtonDesafios.setFocusPainted(false);
        jButtonDesafios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDesafiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonDesafiosMouseExited(evt);
            }
        });
        jButtonDesafios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesafiosActionPerformed(evt);
            }
        });

        jButtonRelatorio.setBackground(new java.awt.Color(0, 17, 32));
        jButtonRelatorio.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButtonRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/relatorio.png"))); // NOI18N
        jButtonRelatorio.setText("  Relatório");
        jButtonRelatorio.setBorder(null);
        jButtonRelatorio.setBorderPainted(false);
        jButtonRelatorio.setContentAreaFilled(false);
        jButtonRelatorio.setFocusPainted(false);
        jButtonRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRelatorioMouseExited(evt);
            }
        });
        jButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUsuarioLayout = new javax.swing.GroupLayout(jPanelUsuario);
        jPanelUsuario.setLayout(jPanelUsuarioLayout);
        jPanelUsuarioLayout.setHorizontalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUsuarioLayout.createSequentialGroup()
                .addGap(0, 71, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(70, 70, 70))
            .addComponent(jLabelNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmailUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDesafios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelUsuarioLayout.setVerticalGroup(
            jPanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNomeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmailUsuario)
                .addGap(50, 50, 50)
                .addComponent(jButtonHome)
                .addGap(40, 40, 40)
                .addComponent(jButtonEditarUsuario)
                .addGap(40, 40, 40)
                .addComponent(jButtonDesafios)
                .addGap(40, 40, 40)
                .addComponent(jButtonGrupos)
                .addGap(40, 40, 40)
                .addComponent(jButtonRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSair)
                .addGap(30, 30, 30))
        );

        jPanelLogo.setBackground(new java.awt.Color(255, 255, 255));

        ImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/600.png"))); // NOI18N

        javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
        jPanelLogo.setLayout(jPanelLogoLayout);
        jPanelLogoLayout.setHorizontalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(ImagemLogo)
                .addGap(24, 24, 24))
        );
        jPanelLogoLayout.setVerticalGroup(
            jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagemLogo))
        );

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addComponent(jPanelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addComponent(jPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarUsuarioMouseEntered
        jButtonEditarUsuario.setContentAreaFilled(rootPaneCheckingEnabled);
        jButtonEditarUsuario.setOpaque(true);
        jButtonEditarUsuario.setBackground(new Color(0, 19, 34));
    }//GEN-LAST:event_jButtonEditarUsuarioMouseEntered

    private void jButtonEditarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarUsuarioMouseExited
        jButtonEditarUsuario.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonEditarUsuarioMouseExited

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
        Login login = new Login(controller);
        login.setVisible(true);
        login.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGruposActionPerformed
        Grupos grupos = new Grupos(this, this.controller, this.u);
        abrirPanelForm(grupos);
    }//GEN-LAST:event_jButtonGruposActionPerformed

    private void jButtonEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarUsuarioActionPerformed
        EditarUser painel = new EditarUser(this, controller, u);
        abrirPanelForm(painel);
    }//GEN-LAST:event_jButtonEditarUsuarioActionPerformed

    private void jButtonHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseEntered
        jButtonHome.setContentAreaFilled(rootPaneCheckingEnabled);
        jButtonHome.setOpaque(true);
        jButtonHome.setBackground(new Color(0, 19, 34));
    }//GEN-LAST:event_jButtonHomeMouseEntered

    private void jButtonHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomeMouseExited
        jButtonHome.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonHomeMouseExited

    private void jButtonDesafiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesafiosActionPerformed
        Desafios desafios = new Desafios(this, controller, u);
        abrirPanelForm(desafios);
    }//GEN-LAST:event_jButtonDesafiosActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        jPanelLogo.removeAll();
        jPanelLogo.setLayout(new java.awt.FlowLayout()); // ou null / BorderLayout, se quiser

        jPanelLogo.add(ImagemLogo);
        jPanelLogo.revalidate();
        jPanelLogo.repaint();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseEntered
        jButtonSair.setContentAreaFilled(rootPaneCheckingEnabled);
        jButtonSair.setOpaque(true);
        jButtonSair.setBackground(new Color(0, 19, 34));
    }//GEN-LAST:event_jButtonSairMouseEntered

    private void jButtonSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseExited
        jButtonSair.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonSairMouseExited

    private void jButtonDesafiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDesafiosMouseEntered
        jButtonDesafios.setContentAreaFilled(rootPaneCheckingEnabled);
        jButtonDesafios.setOpaque(true);
        jButtonDesafios.setBackground(new Color(0, 19, 34));
    }//GEN-LAST:event_jButtonDesafiosMouseEntered

    private void jButtonGruposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGruposMouseEntered
        jButtonGrupos.setContentAreaFilled(rootPaneCheckingEnabled);
        jButtonGrupos.setOpaque(true);
        jButtonGrupos.setBackground(new Color(0, 19, 34));
    }//GEN-LAST:event_jButtonGruposMouseEntered

    private void jButtonDesafiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDesafiosMouseExited
        jButtonDesafios.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonDesafiosMouseExited

    private void jButtonGruposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGruposMouseExited
        jButtonGrupos.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonGruposMouseExited

    private void jButtonRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelatorioMouseEntered
        jButtonRelatorio.setContentAreaFilled(rootPaneCheckingEnabled);
        jButtonRelatorio.setOpaque(true);
        jButtonRelatorio.setBackground(new Color(0, 19, 34));
    }//GEN-LAST:event_jButtonRelatorioMouseEntered

    private void jButtonRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelatorioMouseExited
        jButtonRelatorio.setContentAreaFilled(false);
    }//GEN-LAST:event_jButtonRelatorioMouseExited

    private void jButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioActionPerformed
        Relatorio relatorio = new Relatorio(u);
        abrirPanelForm(relatorio);
    }//GEN-LAST:event_jButtonRelatorioActionPerformed

    public void abrirPanelForm(JPanel panel) {
        jPanelLogo.removeAll(); // ou o painel onde você quer exibir o conteúdo
        panel.setSize(jPanelLogo.getSize());
        panel.setLocation(0, 0);
        jPanelLogo.setLayout(null); // ou BorderLayout se preferir que se ajuste automaticamente
        jPanelLogo.add(panel);
        jPanelLogo.revalidate();
        jPanelLogo.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagemLogo;
    private javax.swing.JButton jButtonDesafios;
    private javax.swing.JButton jButtonEditarUsuario;
    private javax.swing.JButton jButtonGrupos;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonRelatorio;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEmailUsuario;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelLogo;
    private javax.swing.JPanel jPanelUsuario;
    // End of variables declaration//GEN-END:variables

    public void updateInfo() {
        this.jLabelNomeUsuario.setText(this.u.getNome());
        this.jLabelEmailUsuario.setText(this.u.getEmail());
    }
}
