package view;

import controller.TodoController;
import exceptions.AccessDeniedException;
import exceptions.EntityNotFoundException;
import exceptions.InvalidObjectException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.Usuario;

/**
 *
 * @author boli6
 */
public class Login extends javax.swing.JFrame {

    private TodoController controller;

    /**
     * Creates new form Login
     */
    public Login(TodoController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        gifEmailLogin = new javax.swing.JLabel();
        gifSenhaLogin = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonLogar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonCadastrar = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelMsgErroLogin = new javax.swing.JLabel();
        Cadastro = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmailSignUp = new javax.swing.JTextField();
        jButtonCadastrarSignUp = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPasswordFieldSignUp = new javax.swing.JPasswordField();
        gifEmailCadastrar = new javax.swing.JLabel();
        gifSenhaCadastrar = new javax.swing.JLabel();
        jButtonLogarSignUp = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        gifUserCadastrar = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelMsgErroCadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelCentral.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanelCentral.setLayout(null);

        Logo.setBackground(new java.awt.Color(0, 17, 31));
        Logo.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagem.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 125, 62));
        jLabel5.setText("© 2025 TÔ DOIDO. All rights reserved.");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(LogoLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanelCentral.add(Logo);
        Logo.setBounds(0, 0, 400, 500);

        Login.setBackground(new java.awt.Color(255, 255, 255));
        Login.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 17, 33));
        jLabel3.setText("LOGIN");

        gifEmailLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gifEmailLogin.setForeground(new java.awt.Color(0, 17, 33));
        gifEmailLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-mensagem.gif"))); // NOI18N

        gifSenhaLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gifSenhaLogin.setForeground(new java.awt.Color(0, 17, 33));
        gifSenhaLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trancar.gif"))); // NOI18N

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(0, 17, 33));
        jPasswordField1.setBorder(null);

        jButtonLogar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogar.setForeground(new java.awt.Color(0, 17, 32));
        jButtonLogar.setText("Sign In");
        jButtonLogar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        jButtonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 17, 32));
        jSeparator1.setForeground(new java.awt.Color(0, 17, 32));
        jSeparator1.setPreferredSize(new java.awt.Dimension(100, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 17, 32));
        jSeparator2.setForeground(new java.awt.Color(0, 17, 32));

        jButtonCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastrar.setForeground(new java.awt.Color(0, 17, 32));
        jButtonCadastrar.setText("Sign Up");
        jButtonCadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jTextFieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setForeground(new java.awt.Color(0, 17, 33));
        jTextFieldEmail.setBorder(null);

        jLabelMsgErroLogin.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabelMsgErroLogin.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMsgErroLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gifEmailLogin)
                    .addComponent(gifSenhaLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMsgErroLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(jPasswordField1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addComponent(jButtonLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldEmail))
                .addGap(32, 32, 32))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(66, 66, 66)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gifEmailLogin)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gifSenhaLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabelMsgErroLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanelCentral.add(Login);
        Login.setBounds(400, 0, 400, 500);

        Cadastro.setBackground(new java.awt.Color(255, 255, 255));
        Cadastro.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 17, 33));
        jLabel6.setText("CREATE ACCOUNT");

        jTextFieldEmailSignUp.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldEmailSignUp.setForeground(new java.awt.Color(0, 17, 33));
        jTextFieldEmailSignUp.setBorder(null);

        jButtonCadastrarSignUp.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastrarSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCadastrarSignUp.setForeground(new java.awt.Color(0, 17, 32));
        jButtonCadastrarSignUp.setText("Sign Up");
        jButtonCadastrarSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        jButtonCadastrarSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarSignUpActionPerformed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 17, 32));
        jSeparator4.setForeground(new java.awt.Color(0, 17, 32));
        jSeparator4.setPreferredSize(new java.awt.Dimension(100, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 17, 32));
        jSeparator3.setForeground(new java.awt.Color(0, 17, 32));

        jPasswordFieldSignUp.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordFieldSignUp.setForeground(new java.awt.Color(0, 17, 33));
        jPasswordFieldSignUp.setBorder(null);

        gifEmailCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gifEmailCadastrar.setForeground(new java.awt.Color(0, 17, 33));
        gifEmailCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-mensagem.gif"))); // NOI18N

        gifSenhaCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gifSenhaCadastrar.setForeground(new java.awt.Color(0, 17, 33));
        gifSenhaCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-trancar.gif"))); // NOI18N

        jButtonLogarSignUp.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLogarSignUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLogarSignUp.setForeground(new java.awt.Color(0, 17, 32));
        jButtonLogarSignUp.setText("Sign In");
        jButtonLogarSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 17, 33), 1, true));
        jButtonLogarSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogarSignUpActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 17, 32));
        jSeparator5.setForeground(new java.awt.Color(0, 17, 32));
        jSeparator5.setPreferredSize(new java.awt.Dimension(100, 10));

        gifUserCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gifUserCadastrar.setForeground(new java.awt.Color(0, 17, 33));
        gifUserCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-usuário.gif"))); // NOI18N

        jTextFieldNome.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNome.setForeground(new java.awt.Color(0, 17, 33));
        jTextFieldNome.setBorder(null);

        jLabelMsgErroCadastro.setFont(new java.awt.Font("Microsoft Tai Le", 0, 12)); // NOI18N
        jLabelMsgErroCadastro.setForeground(new java.awt.Color(255, 0, 0));
        jLabelMsgErroCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout CadastroLayout = new javax.swing.GroupLayout(Cadastro);
        Cadastro.setLayout(CadastroLayout);
        CadastroLayout.setHorizontalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addGroup(CadastroLayout.createSequentialGroup()
                            .addComponent(gifUserCadastrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CadastroLayout.createSequentialGroup()
                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gifEmailCadastrar)
                            .addComponent(gifSenhaCadastrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMsgErroCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(CadastroLayout.createSequentialGroup()
                                    .addComponent(jButtonCadastrarSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonLogarSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        CadastroLayout.setVerticalGroup(
            CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gifUserCadastrar)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gifEmailCadastrar)
                    .addComponent(jTextFieldEmailSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPasswordFieldSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gifSenhaCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(CadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLogarSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelMsgErroCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanelCentral.add(Cadastro);
        Cadastro.setBounds(800, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        animarParaCadastro();
        jTextFieldEmail.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLogarSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarSignUpActionPerformed
        animarParaLogin();
        jTextFieldNome.setText("");
        jTextFieldEmailSignUp.setText("");
        jPasswordFieldSignUp.setText("");
    }//GEN-LAST:event_jButtonLogarSignUpActionPerformed

    private void jButtonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogarActionPerformed
        try {
            String email = jTextFieldEmail.getText();
            String senha = jPasswordField1.getText();
            
            Usuario u = controller.login(senha, email);
            
            this.dispose();
            Dashboard d = new Dashboard(controller, u);
            d.pack();
            d.setVisible(true);
            d.setLocationRelativeTo(null);
            
        } catch (NoSuchAlgorithmException | SQLException | EntityNotFoundException | AccessDeniedException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButtonLogarActionPerformed

    private void jButtonCadastrarSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarSignUpActionPerformed
        try {
            Usuario u = new Usuario();
            u.setNome(jTextFieldNome.getText());
            u.setEmail(jTextFieldEmailSignUp.getText());
            u.setSenhaHash(jPasswordFieldSignUp.getText());
            u.setDataCriacao(LocalDate.now());
            u.setAdmin(false);

            controller.createUser(u);
            
            jTextFieldNome.setText("");
            jTextFieldEmailSignUp.setText("");
            jPasswordFieldSignUp.setText("");
            animarParaLogin();
        } catch (InvalidObjectException | SQLException | NoSuchAlgorithmException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButtonCadastrarSignUpActionPerformed

    private void animarParaCadastro() {
        // Define posições fixas de início
        int logoStartX = 0;
        int loginStartX = 400;
        int signupStartX = 800;

        // Define posições finais
        int logoEndX = 400;
        int loginEndX = 800;
        int signupEndX = 0; // <- CADASTRO FICA À ESQUERDA DA LOGO

        // Posiciona os painéis nas posições corretas antes da animação
        Logo.setLocation(logoStartX, 0);
        Login.setLocation(loginStartX, 0);
        Cadastro.setLocation(signupStartX, 0);
        Login.setVisible(true);
        Cadastro.setVisible(true);

        Timer timer = new Timer(5, null);
        timer.addActionListener(new ActionListener() {
            int dx = 0;

            public void actionPerformed(ActionEvent e) {
                if (dx < 400) {
                    Logo.setLocation(logoStartX + dx, 0);          // 0 → 400
                    Login.setLocation(loginStartX + dx, 0);        // 400 → 800
                    Cadastro.setLocation(signupStartX - dx, 0);     // 800 → 0
                    dx += 4;
                } else {
                    Logo.setLocation(logoEndX, 0);
                    Login.setLocation(loginEndX, 0);
                    Cadastro.setLocation(signupEndX, 0);
                    timer.stop();
                    Login.setVisible(false); // opcional
                }
            }
        });
        timer.start();
    }

    private void animarParaLogin() {
        int logoStartX = 400;
        int loginStartX = 800;
        int signupStartX = 0;

        int logoEndX = 0;
        int loginEndX = 400;
        int signupEndX = 800;

        Logo.setLocation(logoStartX, 0);
        Login.setLocation(loginStartX, 0);
        Cadastro.setLocation(signupStartX, 0);
        Login.setVisible(true);
        Cadastro.setVisible(true);

        Timer timer = new Timer(5, null);
        timer.addActionListener(new ActionListener() {
            int dx = 0;

            public void actionPerformed(ActionEvent e) {
                if (dx < 400) {
                    Logo.setLocation(logoStartX - dx, 0);          // 400 → 0
                    Login.setLocation(loginStartX - dx, 0);        // 800 → 400
                    Cadastro.setLocation(signupStartX + dx, 0);     // 0 → 800
                    dx += 4;
                } else {
                    Logo.setLocation(logoEndX, 0);
                    Login.setLocation(loginEndX, 0);
                    Cadastro.setLocation(signupEndX, 0);
                    timer.stop();
                    Cadastro.setVisible(false);
                }
            }
        });
        timer.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastro;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Logo;
    private javax.swing.JLabel gifEmailCadastrar;
    private javax.swing.JLabel gifEmailLogin;
    private javax.swing.JLabel gifSenhaCadastrar;
    private javax.swing.JLabel gifSenhaLogin;
    private javax.swing.JLabel gifUserCadastrar;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCadastrarSignUp;
    private javax.swing.JButton jButtonLogar;
    private javax.swing.JButton jButtonLogarSignUp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelMsgErroCadastro;
    private javax.swing.JLabel jLabelMsgErroLogin;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordFieldSignUp;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmailSignUp;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
