package view.elementos;

import controller.TodoController;
import exceptions.EntityNotFoundException;
import java.awt.Color;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import model.Desafio;
import model.Tarefa;
import model.Usuario;
import view.Dashboard;
import view.Panels.Desafio.Detalhes;
import view.Panels.Desafio.EditarDesafio;

/**
 *
 * @author boli6
 */
public class CardDesafio extends javax.swing.JPanel {

    private Dashboard dashboard;
    private TodoController c;
    private Usuario u;
    private Desafio d;

    /**
     * Creates new form NewJPanel
     */
    public CardDesafio(Dashboard dashboard, TodoController c, Usuario u, Desafio d) {
        this.dashboard = dashboard;
        this.c = c;
        this.u = u;
        this.d = d;
        initComponents();
        roundedPanel1.setPreferredSize(new java.awt.Dimension(400, 345)); 
        atualizarInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new view.elementos.RoundedPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        roundedPanelPrazo = new view.elementos.RoundedPanel();
        jLabelInicioFim = new javax.swing.JLabel();
        painelCirculoProgresso = new view.elementos.PainelCirculo();
        jLabelFeitaExistentes = new javax.swing.JLabel();
        botaoModernoEditar = new view.elementos.BotaoModerno();
        botaoModernoExcluir = new view.elementos.BotaoModerno();
        botaoModernoDetalhes = new view.elementos.BotaoModerno();
        jPanel_progress = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        roundedPanel1.setBackground(new java.awt.Color(0, 17, 33));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(540, 300));

        jLabelNome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Projeto Java");

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescricao.setText("Finalizar 5 tarefas");

        roundedPanelPrazo.setBackground(new java.awt.Color(255, 255, 255));

        jLabelInicioFim.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        jLabelInicioFim.setForeground(new java.awt.Color(0, 17, 33));
        jLabelInicioFim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInicioFim.setText("Início: 10/07/2025 | Fim: 30/07/2025");

        javax.swing.GroupLayout roundedPanelPrazoLayout = new javax.swing.GroupLayout(roundedPanelPrazo);
        roundedPanelPrazo.setLayout(roundedPanelPrazoLayout);
        roundedPanelPrazoLayout.setHorizontalGroup(
            roundedPanelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelPrazoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInicioFim, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundedPanelPrazoLayout.setVerticalGroup(
            roundedPanelPrazoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanelPrazoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInicioFim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelCirculoProgresso.setCor(new java.awt.Color(64, 126, 63));

        jLabelFeitaExistentes.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelFeitaExistentes.setForeground(new java.awt.Color(0, 17, 33));
        jLabelFeitaExistentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFeitaExistentes.setText("5/10");

        javax.swing.GroupLayout painelCirculoProgressoLayout = new javax.swing.GroupLayout(painelCirculoProgresso);
        painelCirculoProgresso.setLayout(painelCirculoProgressoLayout);
        painelCirculoProgressoLayout.setHorizontalGroup(
            painelCirculoProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCirculoProgressoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFeitaExistentes, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelCirculoProgressoLayout.setVerticalGroup(
            painelCirculoProgressoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCirculoProgressoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFeitaExistentes, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoModernoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        botaoModernoEditar.setPreferredSize(new java.awt.Dimension(67, 40));
        botaoModernoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModernoEditarActionPerformed(evt);
            }
        });

        botaoModernoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lixo.png"))); // NOI18N
        botaoModernoExcluir.setPreferredSize(new java.awt.Dimension(67, 40));
        botaoModernoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModernoExcluirActionPerformed(evt);
            }
        });

        botaoModernoDetalhes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/detalhes.png"))); // NOI18N
        botaoModernoDetalhes.setPreferredSize(new java.awt.Dimension(67, 40));
        botaoModernoDetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModernoDetalhesActionPerformed(evt);
            }
        });

        jPanel_progress.setBackground(new java.awt.Color(0, 17, 33));
        jPanel_progress.setPreferredSize(new java.awt.Dimension(416, 31));

        javax.swing.GroupLayout jPanel_progressLayout = new javax.swing.GroupLayout(jPanel_progress);
        jPanel_progress.setLayout(jPanel_progressLayout);
        jPanel_progressLayout.setHorizontalGroup(
            jPanel_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        jPanel_progressLayout.setVerticalGroup(
            jPanel_progressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roundedPanelPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(painelCirculoProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(botaoModernoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(botaoModernoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(botaoModernoDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel_progress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescricao)
                .addGap(18, 18, 18)
                .addComponent(roundedPanelPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(painelCirculoProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoModernoDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoModernoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoModernoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 583, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoModernoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModernoEditarActionPerformed
        EditarDesafio ed = new EditarDesafio(dashboard, c, u, d);
        dashboard.abrirPanelForm(ed);
    }//GEN-LAST:event_botaoModernoEditarActionPerformed

    private void botaoModernoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModernoExcluirActionPerformed
        try {
            c.deleteChallenge(this.d.getId());
        } catch (SQLException | EntityNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardDesafio.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_botaoModernoExcluirActionPerformed

    private void botaoModernoDetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModernoDetalhesActionPerformed
        Detalhes detalhes = new Detalhes(dashboard, c, u, d);
        dashboard.abrirPanelForm(detalhes);
    }//GEN-LAST:event_botaoModernoDetalhesActionPerformed

    public void atualizarCorCirculo(int feitas, int total) {
        java.awt.Color cor;

        if (feitas >= total) {
            cor = new Color(64,126,63); // Verde
        } else {
            cor = new Color(211,214,30); // Amarelo
        }

        painelCirculoProgresso.setCor(cor);
        jLabelFeitaExistentes.setText(feitas + "/" + total);
    }

    private void atualizarInfo() {
        try {
            this.jLabelNome.setText(this.d.getNome());
            this.jLabelDescricao.setText(this.d.getDescricao());
            this.jLabelInicioFim.setText(
                    "Inicio: " + this.d.getDataInicio().toString()
                    + " | "
                    + "Fim: " + this.d.getDataFim().toString()
            );

            List<Tarefa> tarefas = c.listarTarefasPorDesafio(this.d.getId());
            int feitas = 0;
            for (Tarefa t : tarefas) {
                if (t.getConcluida()) {
                    feitas++;
                }
            }
            
            int conclusao = (int) (((float) feitas / tarefas.size()) * 100);
            ProgressBarModerna pgm = new ProgressBarModerna(conclusao);
            jPanel_progress.add(pgm);
            atualizarCorCirculo(feitas, tarefas.size());
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(CardDesafio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.elementos.BotaoModerno botaoModernoDetalhes;
    private view.elementos.BotaoModerno botaoModernoEditar;
    private view.elementos.BotaoModerno botaoModernoExcluir;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelFeitaExistentes;
    private javax.swing.JLabel jLabelInicioFim;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_progress;
    private view.elementos.PainelCirculo painelCirculoProgresso;
    private view.elementos.RoundedPanel roundedPanel1;
    private view.elementos.RoundedPanel roundedPanelPrazo;
    // End of variables declaration//GEN-END:variables
}
