package view.elementos;

import controller.TodoController;
import exceptions.EntityNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.GrupoTarefas;
import model.Tarefa;
import view.Dashboard;
import view.Panels.Tarefas.EditarTarefa;

/**
 *
 * @author boli6
 */
public class CardTarefas extends javax.swing.JPanel {

    private Dashboard d;
    private GrupoTarefas g;
    private TodoController c;
    private Tarefa t;

    /**
     * Creates new form CardTarefas
     */
    public CardTarefas(Dashboard d, GrupoTarefas g, Tarefa t, TodoController c) {
        this.d = d;
        this.g = g;
        this.t = t;
        this.c = c;
        initComponents();
        updateInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new view.elementos.RoundedPanel();
        jLabelNome = new javax.swing.JLabel();
        jLabelDescricao = new javax.swing.JLabel();
        roundedPanel2 = new view.elementos.RoundedPanel();
        jLabelCriacao = new javax.swing.JLabel();
        roundedPanel3 = new view.elementos.RoundedPanel();
        jLabelPrazo = new javax.swing.JLabel();
        roundedPanel4 = new view.elementos.RoundedPanel();
        jLabelPrioridade = new javax.swing.JLabel();
        roundedPanel5 = new view.elementos.RoundedPanel();
        jLabelConcluida = new javax.swing.JLabel();
        botaoModernoEditar = new view.elementos.BotaoModerno();
        botaoModernoExcluir = new view.elementos.BotaoModerno();
        botaoModernoMarcar = new view.elementos.BotaoModerno();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(539, 250));

        roundedPanel1.setBackground(new java.awt.Color(0, 17, 33));

        jLabelNome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNome.setText("Projeto Java");

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabelDescricao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescricao.setText("Finalizar 5 tarefas");

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelCriacao.setForeground(new java.awt.Color(0, 17, 33));
        jLabelCriacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCriacao.setText("Criada Em: 01/07/2025");

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCriacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        roundedPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPrazo.setForeground(new java.awt.Color(0, 17, 33));
        jLabelPrazo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrazo.setText("Prazo: 10/07/2025");

        javax.swing.GroupLayout roundedPanel3Layout = new javax.swing.GroupLayout(roundedPanel3);
        roundedPanel3.setLayout(roundedPanel3Layout);
        roundedPanel3Layout.setHorizontalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPrazo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        roundedPanel3Layout.setVerticalGroup(
            roundedPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPrazo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        roundedPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabelPrioridade.setForeground(new java.awt.Color(0, 17, 33));
        jLabelPrioridade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrioridade.setText("Prioridade: 4");

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPrioridade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPrioridade, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        roundedPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabelConcluida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelConcluida.setForeground(new java.awt.Color(64, 126, 63));
        jLabelConcluida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelConcluida.setText("Concluída");

        javax.swing.GroupLayout roundedPanel5Layout = new javax.swing.GroupLayout(roundedPanel5);
        roundedPanel5.setLayout(roundedPanel5Layout);
        roundedPanel5Layout.setHorizontalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelConcluida, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        roundedPanel5Layout.setVerticalGroup(
            roundedPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelConcluida, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        botaoModernoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        botaoModernoEditar.setPreferredSize(new java.awt.Dimension(67, 40));
        botaoModernoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModernoEditarActionPerformed(evt);
            }
        });

        botaoModernoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lixo.png"))); // NOI18N
        botaoModernoExcluir.setPreferredSize(new java.awt.Dimension(67, 40));
        botaoModernoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModernoExcluirActionPerformed(evt);
            }
        });

        botaoModernoMarcar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marcar.png"))); // NOI18N
        botaoModernoMarcar.setPreferredSize(new java.awt.Dimension(67, 40));
        botaoModernoMarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoModernoMarcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addComponent(botaoModernoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(botaoModernoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoModernoMarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(roundedPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roundedPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(60, 60, 60))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescricao)
                .addGap(31, 31, 31)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roundedPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoModernoMarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoModernoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoModernoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoModernoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModernoEditarActionPerformed
        EditarTarefa et = new EditarTarefa(d, g, t, c);
        d.abrirPanelForm(et);
    }//GEN-LAST:event_botaoModernoEditarActionPerformed

    private void botaoModernoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModernoExcluirActionPerformed
        try {
            this.c.deleteTask(this.t.getId());
        } catch (SQLException | EntityNotFoundException ex) {
            Logger.getLogger(CardTarefas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_botaoModernoExcluirActionPerformed

    private void botaoModernoMarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoModernoMarcarActionPerformed
        try {
            this.t.setConcluida(!this.t.getConcluida());
            this.c.updateTask(t);
        } catch (SQLException | EntityNotFoundException ex) {
            Logger.getLogger(CardTarefas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_botaoModernoMarcarActionPerformed


    private void updateInfo(){
        this.jLabelNome.setText(this.t.getTitulo());
        this.jLabelDescricao.setText(this.t.getDescricao());
        this.jLabelCriacao.setText("Criada em " + this.t.getDataCriacao().toString());
        this.jLabelPrazo.setText("Prazo " +this.t.getPrazo().toString());
        this.jLabelPrioridade.setText("Prioridade " + this.t.getPrioridade());
        this.jLabelConcluida.setText(this.t.getConcluida() ? "Concluida" : "Em andamento");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.elementos.BotaoModerno botaoModernoEditar;
    private view.elementos.BotaoModerno botaoModernoExcluir;
    private view.elementos.BotaoModerno botaoModernoMarcar;
    private javax.swing.JLabel jLabelConcluida;
    private javax.swing.JLabel jLabelCriacao;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPrazo;
    private javax.swing.JLabel jLabelPrioridade;
    private javax.swing.JPanel jPanel1;
    private view.elementos.RoundedPanel roundedPanel1;
    private view.elementos.RoundedPanel roundedPanel2;
    private view.elementos.RoundedPanel roundedPanel3;
    private view.elementos.RoundedPanel roundedPanel4;
    private view.elementos.RoundedPanel roundedPanel5;
    // End of variables declaration//GEN-END:variables
}
