package view.Panels.Tarefas;

import controller.TodoController;
import exceptions.EntityNotFoundException;
import model.GrupoTarefas;
import view.Dashboard;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Tarefa;
import view.elementos.CardTarefas;
/**
 *
 * @author boli6
 */
public class Tarefas extends javax.swing.JPanel {

    private Dashboard dashboard;
    private GrupoTarefas g;
    private TodoController c;

    /**
     * Creates new form NewJPanel
     */
    public Tarefas(Dashboard d, GrupoTarefas g, TodoController c) {
        this.dashboard = d;
        this.g = g;
        this.c = c;
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(15);
        updateInfoTarefas();
        this.jLabelGrupo.setText(this.g.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jPanelTopo = new javax.swing.JPanel();
        jLabelGrupo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCriarTarefa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelTarefas = new javax.swing.JPanel();

        jPanelCentral.setBackground(new java.awt.Color(0, 17, 33));
        jPanelCentral.setPreferredSize(new java.awt.Dimension(653, 606));

        jPanelTopo.setBackground(new java.awt.Color(0, 17, 33));

        jLabelGrupo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelGrupo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarefas.png"))); // NOI18N
        jLabelGrupo.setText(" Deveres");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jButtonCriarTarefa.setBackground(new java.awt.Color(0, 17, 33));
        jButtonCriarTarefa.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jButtonCriarTarefa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCriarTarefa.setText("Criar Nova Tarefa");
        jButtonCriarTarefa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButtonCriarTarefa.setContentAreaFilled(false);
        jButtonCriarTarefa.setFocusPainted(false);
        jButtonCriarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopoLayout = new javax.swing.GroupLayout(jPanelTopo);
        jPanelTopo.setLayout(jPanelTopoLayout);
        jPanelTopoLayout.setHorizontalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButtonCriarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanelTopoLayout.setVerticalGroup(
            jPanelTopoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopoLayout.createSequentialGroup()
                .addComponent(jLabelGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCriarTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanelTarefas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelTarefasLayout = new javax.swing.GroupLayout(jPanelTarefas);
        jPanelTarefas.setLayout(jPanelTarefasLayout);
        jPanelTarefasLayout.setHorizontalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        jPanelTarefasLayout.setVerticalGroup(
            jPanelTarefasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanelTarefas);

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTopo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addComponent(jPanelTopo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCriarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarTarefaActionPerformed
        CriarTarefa criar = new CriarTarefa(dashboard, g, c);
        dashboard.abrirPanelForm(criar);
    }//GEN-LAST:event_jButtonCriarTarefaActionPerformed

    private void updateInfoTarefas() {

        try {
            zerarComponentes();
            List<Tarefa> tarefas = c.findAllTasks(this.g.getId());

            int y = 20;
            int espacamento = 20;

            for (Tarefa t : tarefas) {
                CardTarefas ct = new CardTarefas(dashboard, g, t, c);
                int altura = ct.getPreferredSize().height;
                int largura = ct.getPreferredSize().width;

                ct.setBounds(44, y, largura, altura);
                ct.setVisible(true);
                jPanelTarefas.add(ct);
                y += altura + espacamento; // espaço entre os cards
            }
            jPanelTarefas.revalidate();
            jPanelTarefas.repaint();

        } catch (EntityNotFoundException | SQLException ex) {
            Logger.getLogger(Tarefas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        } 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarTarefa;
    private javax.swing.JLabel jLabelGrupo;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelTarefas;
    private javax.swing.JPanel jPanelTopo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void zerarComponentes() {
        jPanelTarefas.removeAll();
        jPanelTarefas.revalidate();
        jPanelTarefas.repaint();
    }
}
